// 候補として、半母音も含める
export const vowels_grouped_by_chars: { [key: string]: string[] } = {
  a: ['a', 'ai', 'ao', 'an', 'ang'],
  o: ['o', 'ou', 'ong'],
  e: ['e', 'ei', 'er', 'en', 'eng', 'wen', 'weng'],
  ai: ['ai', 'wai', 'yai'],
  ei: ['ei', 'wei'],
  ao: ['ao', 'yao'],
  ou: ['ou', 'you'],
  er: ['er'],
  an: ['an', 'ang', 'wan', 'yan', 'wang', 'yang'],
  en: ['en', 'eng', 'wen', 'weng'],
  ang: ['ang', 'wang', 'yang'],
  on: ['ong', 'yong'],
  ong: ['ong', 'yong'],
  eng: ['eng', 'weng'],
  u: [
    'u',
    'un',
    'ui',
    'uo',
    'ue',
    'ua',
    'uan',
    'uai',
    'uang',
    'wu',
    'wo',
    'wa',
    'wai',
    'wan',
    'wang',
  ],
  v: ['v', 've', 'yu', 'yue'],
  i: [
    'i',
    'in',
    'iu',
    'ie',
    'ia',
    'ing',
    'ian',
    'iao',
    'iang',
    'iong',
    'yi',
    'ye',
    'ya',
    'yao',
    'yin',
    'yan',
    'ying',
    'yang',
    'yong',
  ],
  un: ['un'],
  in: ['in', 'ing', 'yin', 'ying'],
  ui: ['ui'],
  uo: ['uo', 'wo'],
  iu: ['iu'],
  ve: ['ve', 'yue'],
  ie: ['ie', 'ye'],
  ue: ['ue'],
  ua: ['ua', 'uan', 'uai', 'uang', 'wa', 'wai', 'wan', 'wang', 'yuan'],
  ia: ['ia', 'ian', 'iao', 'iang', 'ya', 'yao', 'yan', 'yang'],
  ing: ['ing', 'ying'],
  uan: ['uan', 'uang', 'wan', 'wang', 'yuan'],
  ian: ['ian', 'iang', 'yan', 'yang'],
  iao: ['iao', 'yao'],
  uai: ['uai', 'wai'],
  uang: ['uang', 'wang'],
  iang: ['iang', 'yang'],
  io: ['iong', 'yong'],
  ion: ['iong', 'yong'],
  iong: ['iong', 'yong'],
  y: [
    'yi',
    'yu',
    'ye',
    'ya',
    'yue',
    'you',
    'yao',
    'yai',
    'yin',
    'yun',
    'yan',
    'yuan',
    'ying',
    'yang',
    'yong',
  ],
  yi: ['yi', 'yin', 'ying'],
  w: ['wu', 'wo', 'wa', 'wei', 'wai', 'wen', 'wan', 'wang', 'weng'],
  wu: ['wu'],
  yu: ['yu', 'yue', 'yun', 'yuan'],
  wo: ['wo'],
  ye: ['ye'],
  ya: ['ya', 'yao', 'yai', 'yan', 'yang'],
  wa: ['wa', 'wai', 'wan', 'wang'],
  we: ['wei', 'wen', 'weng'],
  wei: ['wei'],
  yue: ['yue'],
  yo: ['you', 'yong'],
  you: ['you'],
  yao: ['yao'],
  wai: ['wai'],
  yai: ['yai'],
  yin: ['yin', 'ying'],
  wen: ['wen', 'weng'],
  yun: ['yun'],
  wan: ['wan', 'wang'],
  yan: ['yan', 'yang'],
  yua: ['yuan'],
  yuan: ['yuan'],
  ying: ['ying'],
  wang: ['wang'],
  yang: ['yang'],
  yon: ['yong'],
  yong: ['yong'],
  weng: ['weng'],
};
